#!/bin/bash

MYSQL_DATABASE=$DATABASE_NAME
MYSQL_USER=$DATABASE_USER
MYSQL_PASSWORD=$DATABASE_PASSWORD
MYSQL_PATH="/usr/local/mysql/bin/mysql" # TODO: make this environment aware
MYSQL_ARTIST_TABLE_NAME="artists"

echo "Deleting..."
"$MYSQL_PATH" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "DROP DATABASE $MYSQL_DATABASE"

echo "Creating database..."
"$MYSQL_PATH" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "CREATE DATABASE $MYSQL_DATABASE CHARACTER SET utf8 COLLATE utf8_general_ci";
"$MYSQL_PATH" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "SHOW DATABASES"

echo "Creating tables..."
"$MYSQL_PATH" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; CREATE TABLE $MYSQL_ARTIST_TABLE_NAME(
  id int(11) unsigned NOT NULL AUTO_INCREMENT, 
  name varchar(100) NOT NULL, 
  PRIMARY KEY (id)
  );"

echo "Inserting data..."
"$MYSQL_PATH" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; INSERT INTO $MYSQL_ARTIST_TABLE_NAME (name)
VALUES ('Bonobo');
"

echo "Finishing up..."
"$MYSQL_PATH" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -D "$MYSQL_DATABASE" -e "USE $MYSQL_DATABASE; SHOW TABLES"
